### ISSUE TITLE
Installing into a conda virtual environment

### ISSUE THREAD

**Issue by breisfeld** [BenevolentAI/guacamol_baselines#10]
For those people interested in installing the package into a conda virtual environment, I was successful using the following:

```
$ conda create -n guacamol -c conda-forge rdkit python=3.7
$ conda activate guacamol
```

The `requirements.txt` file in the repo seems incorrect.

I changed `git+https://github.com/molecularsets/moses.git@master#egg=moses` to 
`git+https://github.com/molecularsets/moses.git@master#egg=molsets` 

Also, the version of `numpy` needs to be updated because of the `tensorflow` requirements. The final `requirements.txt` file looked like

```
guacamol==0.5.3
matplotlib==3.0.2
torch>=1.0.0
joblib==0.12.5
numpy==1.18
tqdm==4.26.0
cython==0.29
nltk==3.4.5
flake8==3.5.0
git+https://github.com/molecularsets/moses.git@master#egg=molsets
``` 

After installing `git-lfs`, I then installed the other required packages:

```
$ pip install -r requirements.txt
```

**Comment by JoshuaMeyers** [comment]
Hey Brad, thanks for the information and for pointing out the inconsistency in `requirements.txt`. The above solution will work when using some of the models in the baselines repo, but to use the models from the moses suite I believe you will need to revert to an old version of the moses code (the package has been renamed to molsets more recently).

Unfortunately the GuacaMol baselines predate the availability of Moses on PyPi but a preliminary search suggests that using `git+https://github.com/molecularsets/moses.git@96c77d52c688dcac8e2962d78965175e7824c48c#egg=moses` in `requirements.txt` should work.

As you also point out, there are a number of dependencies whose versions have drifted, particularly `numpy` and `keras` (required by FCD). We will aim to submit a PR for these changes soon.

**Comment by breisfeld** [comment]
Hi Joshua, I appreciate the comments. I'll give that Moses branch a try and stay tuned for updates to the GuacaMol repo.

**Comment by JoshuaMeyers** [comment]
Hey @breisfeld, the installation issues should be resolved by https://github.com/BenevolentAI/guacamol_baselines/pull/14. Thanks for raising
