### ISSUE TITLE
molecular names 

### ISSUE THREAD

**Issue by shahik** [BenevolentAI/guacamol_baselines#7]
Hi, 
    thanks for the code release. I am training on my small data (50 smiles) and each time ' Celecoxib rediscovery
Troglitazone rediscovery' names appear also on guacamol dataset these names appear what are these names related to? thanks!

**Comment by JoshuaMeyers** [comment]
Hi @shahik, thanks for your interest. The rediscovery tasks such as celecoxib and troglitazone are described in our paper: https://pubs.acs.org/doi/10.1021/acs.jcim.8b00839. Your dataset has no effect on which tasks are given to the generator, although it will impact the comparability of results to our baseline results

**Comment by shahik** [comment]
these names does not effect generation on my custom dataset. is this correct?

**Comment by JoshuaMeyers** [comment]
Yes, your dataset only affects your trained generator.

The drug names are downstream tasks
