### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by shahik** [BenevolentAI/guacamol_baselines#8]
Hi, 
   I get this error while training on Hill climbing & PPO on google colab. It works fine on colab None option. 
any solution Plz?

**Comment by JoshuaMeyers** [comment]
Hey @shahik, apologies I'm not familiar with the setup on colab. But it appears that your environment is not initialised correctly. Might be worth looking for more general solutions for this error (https://discuss.pytorch.org/t/cudnn-status-not-initialized/7090)

**Comment by shahik** [comment]
Solved as, 

!conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

import torch

if torch.cuda.is_available():
  print('GPU available')
else:
  print('Please set GPU via Edit -> Notebook Settings.')
